name: Test sbom utility scripts image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-sbom-utility-scripts-image.yml
      - sbom-utility-scripts/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-sbom-utility-scripts-image.yml
      - sbom-utility-scripts/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run tox checks for base-images-sbom-script
      run: |
        python3 -m pip install tox
        cd ./sbom-utility-scripts/scripts/base-images-sbom-script/app/
        tox

    - name: Run tox checks for merge-sboms-script
      run: |
        python3 -m pip install tox
        cd ./sbom-utility-scripts/scripts/merge-sboms-script/
        tox

    - name: Run tox checks for index-image-sbom-script
      run: |
        python3 -m pip install tox
        cd ./sbom-utility-scripts/scripts/index-image-sbom-script/
        tox

    - name: Run tox checks for add-image-reference-script
      run: |
        python3 -m pip install tox
        cd ./sbom-utility-scripts/scripts/add-image-reference-script/
        tox

    - name: Run tox checks for sbom-for-oci-copy-task
      run: |
        python3 -m pip install tox
        cd ./sbom-utility-scripts/scripts/sbom-for-oci-copy-task/
        tox

    - name: Run tox checks for contextual-sbom
      run: |
        python3 -m pip install tox
        cd ./sbom-utility-scripts/scripts/sbom-for-oci-copy-task/
        tox
